deploy:
  image: python:3.5
  stage: build
  before_script:
    - apt-get update -yqqq
    - apt-get install -yqq xvfb
    - Xvfb :99 -screen 0 1280x720x24 -ac &
    - export DISPLAY=:99
  script: 
  #- pip3 install -U -r /builds/FrankTheTank/newb_actual/skeefooza/requirements.txt
    - pip3 install seaborn
    - pip3 install numpy
    - pip3 install sklearn
    - pip3 install keras
    - pip3 install --upgrade tensorflow
    - python3 -c "import tensorflow as tf; print(tf.__version__)"
    - python3 /builds/FrankTheTank/newb_actual/skeefooza/hello_world.py
