deploy:
  image: python:latest
  stage: build
  script: 
    - pip install -U -r ./skeefooza/requirements.txt
    - python -c "import tensorflow as tf; print(tf.__version__)"
    - python ./skeefooza/hello_world.py
