language: python
python: 
  - "2.7"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - pip install -r skeefooza/requirements.txt
  - python -c "import tensorflow as tf; print(tf.__version__)"
  - python skeefooza/hello_world.py
